error: Convert error handling to 'failure'
We are now using the 'failure' crate to error handling so we avoid a
lot of conversion code and duplication.

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>